apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      description: The GitHub repository URL to clone
    - name: image-reference
      type: string
      description: The IBM Cloud Container Registry image path to build and push to
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)

    - name: npminstall
      taskRef:
        name: npm-install
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: run-tests
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: buildah
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: STORAGE_DRIVER
          value: vfs
